### ISSUE TITLE
Support MC 1.16.4

### ISSUE THREAD

**Issue by redbrain** [LambdAurora/LambdaBetterGrass#10]
I mostly file these as a courtesy; 1.16.4 is the last version of 1.16 and requires minimal changes to support.
Update at your convenience.

**Comment by FlashyReese** [comment]
The 1.16.3 version should just work on 1.16.4.

**Comment by LambdAurora** [comment]
It's already compatible...

The version had so minimal changes that it almost doesn't break anything....
