### ISSUE TITLE
Game Freezes While Using Indium

### ISSUE THREAD

**Issue by TAKfsg** [LambdAurora/LambdaBetterGrass#14]
The Game Freezes while using Indium.

**Comment by CasuallyMatt** [comment]
are you by any chance using the curseforge release of sodium?

**Comment by TAKfsg** [comment]
> are you by any chance using the curseforge release of sodium?
I am using the sodium 1.1 snapshot from github so it is compatible with indium

**Comment by DragonEggBedrockBreaking** [comment]
> I am using the sodium 1.1 snapshot from github so it is compatible with indium

You need to use a fork of sodium for LBG to work.

**Comment by TAKfsg** [comment]
link?

**Comment by DragonEggBedrockBreaking** [comment]
> link?

https://github.com/comp500/sodium-fabric
You need to build it yourself.

**Comment by TAKfsg** [comment]
> > link?
> 
> https://github.com/comp500/sodium-fabric
> You need to build it yourself.

Already have that one

**Comment by DragonEggBedrockBreaking** [comment]
> Already have that one

Then I cannot reproduce this bug. I use LBG with Indium (and sodium fork ofc) and don't have issues

**Comment by TAKfsg** [comment]
> Then I cannot reproduce this bug. I use LBG with Indium (and sodium fork ofc) and don't have issues

here is the latest log:
https://pastebin.com/PUdXnCKE

**Comment by DragonEggBedrockBreaking** [comment]
> > Then I cannot reproduce this bug. I use LBG with Indium (and sodium fork ofc) and don't have issues
> 
> here is the latest log:
> https://pastebin.com/PUdXnCKE

Do you have a crash report (`.minecraft/crash-reports`)?

**Comment by TAKfsg** [comment]
> Do you have a crash report (`.minecraft/crash-reports`)?

there is no crash report because it doesn't crash, it freezes. Read the title lol.

**Comment by DragonEggBedrockBreaking** [comment]
> there is no crash report because it doesn't crash, it freezes. Read the title lol.

Oops. Do you have a log?

**Comment by TAKfsg** [comment]
yeah u replied to it.
https://pastebin.com/PUdXnCKE
here it is again but i already fixed it. I also go by "TAKfsg". U gave me the download to the sodium thingy.
