### ISSUE TITLE
Better Snow doesn't work with the Lightning Rod

### ISSUE THREAD

**Issue by FwuffyPetsOwO** [LambdAurora/LambdaBetterGrass#17]
![2021-06-08_11 45 53](https://user-images.githubusercontent.com/65428450/121240537-4c1ef180-c84f-11eb-993b-72f5ff9a3549.png)

**Comment by LambdAurora** [comment]
This can be solved temporarily with a custom LambdaBetterGrass resource pack.

This will be solved for next release.
