### ISSUE TITLE
Grass path connection

### ISSUE THREAD

**Issue by Aeldit** [LambdAurora/LambdaBetterGrass#29]
I'm not sure if this is a bug or more of an enhancement but the grass path doesn't connects to the one under it, as in the picture below. There is a one pixel gap between the blocks
![2021-10-31_16 01 20](https://user-images.githubusercontent.com/81476169/139589708-2158d5ad-3ead-4cdc-baca-ebead1e2012e.png)

**Comment by ModProg** [comment]
I tried doing this through optifine CTM using [Continuity](https://github.com/PepperCode1/Continuity) but idk if that would even work as you cannot detect if there is a path block in front IIRC
