### ISSUE TITLE
Resource  pack  outdated on  1.18

### ISSUE THREAD

**Issue by ghost** [LambdAurora/LambdaBetterGrass#31]
![image](https://user-images.githubusercontent.com/82549089/144735024-2b13313b-7e2b-437e-acd0-e449a04e818d.png)

**Comment by LambdAurora** [comment]
This is a non-issue, it doesn't prevent the usage of the pack.
I don't see any interest in releasing a new version of the mod, just to change 1 value in the built-in resource packs, while the current version works both in 1.17 and 1.18.

**Comment by ghost** [comment]
> This is a non-issue, it doesn't prevent the usage of the pack. I don't see any interest in releasing a new version of the mod, just to change 1 value in the built-in resource packs, while the current version works both in 1.17 and 1.18.

Okay but you could also include a fix for it when you release another more substational update? I find it annoying, it probably confuses some people

**Comment by LambdAurora** [comment]
It'll be updated if a version cannot support both 1.17 and 1.18 at the same time.
