### ISSUE TITLE
Game Crashes at startup with Mod version 1.2.2

### ISSUE THREAD

**Issue by keatit71** [LambdAurora/LambdaBetterGrass#34]
Minecraft 1.18.1

Java 17

When using Lambda better grass version 1.2.2 the game crashes at startup though using the previous version stops this problem from happening.
[crash-2021-12-30_21.06.38-server.txt](https://github.com/LambdAurora/LambdaBetterGrass/files/7794604/crash-2021-12-30_21.06.38-server.txt)
[crash-2021-12-30_21.06.43-client.txt](https://github.com/LambdAurora/LambdaBetterGrass/files/7794605/crash-2021-12-30_21.06.43-client.txt)

[latest.log](https://github.com/LambdAurora/LambdaBetterGrass/files/7794610/latest.log)

**Comment by LambdAurora** [comment]
Use LBG 1.2.1 for now, or use dependency overrides to bring back SpruceUI 3.3.0
I knew that I forgot one mod out there... Just couldn't remember which.

This is more of a LambdaControls issue tbh.

**Comment by keatit71** [comment]
Not sure how to override dependencies so gonna use old version
