### ISSUE TITLE
Grass connects to obstructed grass

### ISSUE THREAD

**Issue by ModProg** [LambdAurora/LambdaBetterGrass#36]
![2022-01-11_14 29 15](https://user-images.githubusercontent.com/11978847/148951354-a7b83cb2-040f-4be4-b238-6308ae34f5a2.png)

Not sure if this is very urgent to fix, as normally the lower grass will disappear with time anyway.

**Comment by LambdAurora** [comment]
This has been fixed a while ago, but don't remember when.
