### ISSUE TITLE
Torches don't animate with Indium installed (Sodium: Animate Only Visible Textures workaround)

### ISSUE THREAD

**Issue by janitor-raus** [LambdAurora/LambdaBetterGrass#41]
I am not quite certain what's going on. I suspect there might be some mod conflict where the presence of LBG with that other mod causes this to occur but so far I have not found out which one it might be. I will update/reply to this issue as I explore further.

To clarify, it truly *is* caused by its mere presence. Adjusting the settings in any way does not undo the lack of torch animations, only completely removing the mod will. 

Video of the issue:

https://user-images.githubusercontent.com/11655762/153750985-34338f7d-b385-40a2-a278-38fd263654e8.mp4

Using the John Smith Legacy resource pack, among a slew of other client-side mods. If you have any recommendations or ideas on what to test specifically, please let me know. Until then, I'll be checking through a process of elimination.

###      Specs, if relevant:
Minecraft 1.18.1
i7-8700K
RTX 2080

###     Mods list currently in use:

> 3D Skin Layers, Advancements Enlarger, AmbientEnvironment, Animatica, Appleskin, Balm (lib), Beehive Tooltips, Better Dropped Items, Better F3, Better Mount HUD, Blur, CEM (lib), Chat Heads, CIT Resewn, Clean Cut, Clear Skies, Click Through, Client Tweaks, Cloth Config (lib), Clumps, Colormatic, ColorUtility, Continuity, Easier Villager Trading, Effective Splashes, Enchantment Descriptions, Enhanced Block Entities, Entity Culling, Entity View Distance, Extra Sounds, Fabric API (lib), Fabric Skyboxes, Falling Leaves, Farsight, Ferrite Core, Highlighter, Iceberg (lib), Illuminations, Indium (lib), Inventory Profiles Next, Item Borders, Krypton, Lambda Better Grass (this mod), Lambda Dynamic Lights (eyyyy), Lazy DFU, Lithium (lib), Mod Menu, No Telemetry, On Soul Fire, Presence Footsteps, Raised, Reese's Sodium Options, Seamless Loading Screen, Shulkerbox Tooltip, Sodium Extra, Sodium, Spyglass Improvements, Starlight, Tooltip Fix, Visuality, Waystones, Xaero's Mini/World Map.

_Phew, that's a lot._

**Comment by janitor-raus** [comment]
### Test 1
Removed all mods except for the following:

![image](https://user-images.githubusercontent.com/11655762/153751966-b65e1c7a-26cb-47b5-a29c-5254d6f4f889.png)

Problem persists. Real strong vibes that this might not be a mod conflict at all but rather some oversight in LBG. I also forgot to mention that the torch item in-hand animates properly, it's the torches placed that do not. In some very rare cases and _only_ in very particular spots, torches animate, while one placed to the block neighboring it wouldn't. I am not sure if this bears any significance.

**Comment by janitor-raus** [comment]
### Test 2
Further reduced mods to absolute necessary: Fabric, Sodium, Mod Menu and LBG. Torches work as intended. Confirms that there's an odd conflict present with one of the mods previously listed. Continuing tests to isolate the culprit.

**Comment by LambdAurora** [comment]
> ### Test 2
> 
> Further reduced mods to absolute necessary: Fabric, Sodium, Mod Menu and LBG. Torches work as intended. Confirms that there's an odd conflict present with one of the mods previously listed. Continuing tests to isolate the culprit.

If I don't get mistaken, I know Sodium does something to not animate everything if it's not visible, without Indium the models of LBG doesn't work properly

My guess is with Indium, LBG models get used, and it confuses Sodium and thinks torches are not being seen, thus not animating the texture.

**Comment by janitor-raus** [comment]
> > ### Test 2
> > Further reduced mods to absolute necessary: Fabric, Sodium, Mod Menu and LBG. Torches work as intended. Confirms that there's an odd conflict present with one of the mods previously listed. Continuing tests to isolate the culprit.
> 
> If I don't get mistaken, I know Sodium does something to not animate everything if it's not visible, without Indium the models of LBG doesn't work properly
> 
> My guess is with Indium, LBG models get used, and it confuses Sodium and thinks torches are not being seen, thus not animating the texture.

I was about to write a conclusion about that very thing. Indium is indeed the cause in this situation. Unfortunately, I need it so that Continuity will work (connected textures). If I had to choose between the two, I'd rather forgo LBG for the time being. 

At the very least we now know this issue exists so even if you can't possibly implement a workaround or get in touch with the Indium devs to rectify the behavior, it can be listed for people to be aware :)

EDIT: Disabling "Animate Only Visible Textures" under the Performance tab of Sodium does work around it and animate the torches again, though ideally it shouldn't be necessary to do so. It claims the performance impact for this setting is high but honestly I can't tell for sure without some benchmark setting. _Oddly enough it feels as if it's faster with the setting off.. /shrug_

**Comment by janitor-raus** [comment]
Indium's last alpha appears to have made changes related to this matter:
`Fix compatibility with Sodium's "animate only visible textures" option`

I have not tested whether this resolves the issue but I think there's a pretty good chance it did.
