### ISSUE TITLE
Crash if game language isn't English

### ISSUE THREAD

**Issue by slavalamp** [LambdAurora/LambdaBetterGrass#44]
The game crashes at launch if the language isn't English (I've tried Czech and Spanish). It also crashes when I try to change the language from English to something else. It doesn't crash if I have the same set of mods but without LambdaBetterGrass.

Crash log: https://pastebin.com/md59PSTS

Minecraft 1.18.2
LambdaBetterGrass 1.2.2
Inspecio and LambDynamicLights seem to have the same issue.

**Comment by LambdAurora** [comment]
1.18.2 is not yet supported.

**Comment by slavalamp** [comment]
Wow, thanks for fast reply :D
I didn't realize it could be because of the version. I'm looking forward for 1.18.2 support then :D and stay on 1.18.1 for now, because this mod is fantastic, thank you a lot for creating it

P. S. It started to crash with any languages somehow, so that's not just language related ig

**Comment by LambdAurora** [comment]
Fixed.
