### ISSUE TITLE
1.18.2 instant crash

### ISSUE THREAD

**Issue by ghost** [LambdAurora/LambdaBetterGrass#45]
when trying to launch the game in minecraft 1.18.2 it instant crashes (this isn't the case for 1.18.1)

crash log: [crash-2022-03-04_12.26.34-client.txt](https://github.com/LambdAurora/LambdaBetterGrass/files/8188317/crash-2022-03-04_12.26.34-client.txt)

latest.log: [latest.log](https://github.com/LambdAurora/LambdaBetterGrass/files/8188318/latest.log)

mods:
fabric api 0.47.8-1.18.2
fabric loader 0.13.3
lambda better grass 1.2.2 - 1.17
lazy dfu 0.1.2

**Comment by PweSol** [comment]
Can confirm. The mod needs to be updated to 1.18.2.

**Comment by giorov** [comment]
[crash-2022-03-05_13.54.49-client.txt](https://github.com/LambdAurora/LambdaBetterGrass/files/8191543/crash-2022-03-05_13.54.49-client.txt)

**Comment by giorov** [comment]
Confabricate needs updating. not sure if that's dependency for this but it is for some other mods that need updating.

**Comment by NightEule5** [comment]
The mixin for `net.minecraft.class_3304` which maps to `net.minecraft.resource.ReloadableResourceManagerImpl` is failing. The method `method_14475`, which maps to `addPack` in 1.18.1, is missing from 1.18.2's mappings. It must've been removed

**Comment by LambdAurora** [comment]
Fixed.
