### ISSUE TITLE
Not working with modded grass

### ISSUE THREAD

**Issue by StockiesLad** [LambdAurora/LambdaBetterGrass#46]
Fabric 0.13.3
1.18.1
LambdaBetterGrass doesn't apply to unearthed and BYG grass types.
[latest.log](https://github.com/LambdAurora/LambdaBetterGrass/files/8241447/latest.log)

**Comment by LambdAurora** [comment]
This is expected, a resource pack should be made, or direct support should be added into those mods.

LBG provides resource pack abilities for those cases.
