### ISSUE TITLE
Custom snow layer block doesn't connect to plants

### ISSUE THREAD

**Issue by jakeb072001** [LambdAurora/LambdaBetterGrass#47]
I've made my own snow layer block, but it doesn't connect to plants. Is there something in the resource pack for this or is it not possible to fix from my end? I thought of using a mixin to fix it but I don't know how to add this mod to my build.gradle.

Sorry if there's some sort of formatting I should use for issues, just wanted to ask this real quick.

**Comment by LambdAurora** [comment]
Hi, sorry for the response delay but for any custom layers you need to define one via an asset file: https://github.com/LambdAurora/LambdaBetterGrass/tree/1.18/src/main/resources/assets/lambdabettergrass/bettergrass/layer_types

In addition, to that, currently it's not guaranteed that there will be default support, but this might change in the future.

**Comment by jakeb072001** [comment]
Thanks! I was able to get it working. I used your datagen.mjs to add the corrupt_snow layer to everything. Maybe theres a better way to get this working but if it works then it works.

**Comment by LambdAurora** [comment]
The new version I'm currently working on will default layer: true to all data files, so that won't be longer required ;)
