### ISSUE TITLE
Side overlay rendering incorrectly due to different grass model

### ISSUE THREAD

**Issue by mo0dss** [LambdAurora/LambdaBetterGrass#48]
![2022-04-08_21 40 19](https://user-images.githubusercontent.com/74024438/162527465-87b8d796-9e73-48b6-ac82-b79057280d0f.png)
and from the side its just gone
![2022-04-08_21 40 46](https://user-images.githubusercontent.com/74024438/162527502-f665a821-c87c-496e-ab0c-1754d1e9bd8f.png)

**Comment by mo0dss** [comment]
Looking further at the grass model, wynncraft moves the overlay up to give a effect like this
![2022-04-10_14 45 14](https://user-images.githubusercontent.com/74024438/162621193-b194d821-4852-4afe-97e9-638ec9c5ee41.png)
Is there a way to specify what texture or element the overlay will render on?

**Comment by LambdAurora** [comment]
![image](https://github.com/LambdAurora/LambdaBetterGrass/assets/12587332/da4d686c-8eea-4056-916b-890d8672b09d)
Fixed in next release.
