### ISSUE TITLE
1.18.2 version incompatible with LambdaControls

### ISSUE THREAD

**Issue by bwilliance** [LambdAurora/LambdaBetterGrass#49]
1.18.2 version of LambdaBetterGrass works normally on its own, but loading it with the latest version of LambdaControls crashes the game. Loading the latest version of LambdaControls on its own also works normally.
This basically results in me having to choose between the two mods.

Minecraft 1.18.2
LambdaBetterGrass 1.2.3
LambdaControls 1.7.1

Crash message:

The game crashed whilst initializing game
Error: java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'lambdacontrols'!
Exit Code: -1

Crash report:

[crash-2022-04-11_15.51.44-client.txt](https://github.com/LambdAurora/LambdaBetterGrass/files/8468252/crash-2022-04-11_15.51.44-client.txt)

**Comment by LambdAurora** [comment]
LambdaControls 1.18.2 has been abandonned, please use [MidnightControls](https://modrinth.com/mod/midnightcontrols) instead.
