### ISSUE TITLE
[Suggestion] Ability to configure the texture resolution of the connected grass "line" 

### ISSUE THREAD

**Issue by Mangoiz** [LambdAurora/LambdaBetterGrass#57]
![image](https://user-images.githubusercontent.com/107194826/181864559-f8e016c5-e442-4723-be12-d2d09060fa31.png)

Currently, if using a different resource pack, the line will still exist, but if its a different resolution then it stays the same and looks odd with those packs 

I would suggest being able to configure the resolution of this connecting line to avoid things like this happening

![image](https://user-images.githubusercontent.com/107194826/181864670-785968e4-1d42-46d2-b662-67edc0d624c3.png)

**Comment by LambdAurora** [comment]
[This is already configurable through custom resource packs.](https://github.com/LambdAurora/LambdaBetterGrass/blob/1.19/documentation/API.md)
