### ISSUE TITLE
[1.19] [Bug] Mod breaks rendering of Diagonal Fences mod

### ISSUE THREAD

**Issue by Fuzss** [LambdAurora/LambdaBetterGrass#58]
Hey there, my [Diagonal Fences](https://www.curseforge.com/minecraft/mc-mods/diagonal-fences) mod manipulates baked models of fences (by rotating and stretching the extensions) to allow them to show diagonal connections.

Having your mod installed breaks this and the diagonal fence parts don't render. Do you have any idea what could be going wrong and how to fix it?

![](https://media.discordapp.net/attachments/917550806922846299/1003605252714545182/unknown.png)

**Comment by Zarepheth** [comment]
I posted a bit more information in the Lambda Better Grass comments on the CurseForge website.

https://www.curseforge.com/minecraft/mc-mods/lambdabettergrass#c130

**Comment by Fuzss** [comment]
I went ahead and added integration for Lambda Better Grass in Diagonal Fences v4.2.2.
![2022-10-12_14 01 53](https://user-images.githubusercontent.com/28218241/195338320-8663e586-a453-446f-9b0a-3938c07e99fd.png)
