### ISSUE TITLE
Weird Podzol and Nylium textures

### ISSUE THREAD

**Issue by Givoric** [LambdAurora/LambdaBetterGrass#61]
![2022-08-30_13 29 24](https://user-images.githubusercontent.com/93440582/187990908-8540824d-b1c1-470f-b32f-0d13cc903759.png)

**Comment by LambdAurora** [comment]
This might be a bad interaction with another mod and most likely not this mod's fault.

**Comment by Givoric** [comment]
yep, after i updated a bunch of mods it went away, my bad
