### ISSUE TITLE
[Configuration Conflict] - more than one oshi.architecture.properties file on classpath - Fabric 1.19.2

### ISSUE THREAD

**Issue by xR4YM0ND** [LambdAurora/LambdaBetterGrass#65]
Line 1506 - 1534

Full Client [latest.log](https://gist.github.com/SpigotDE/b3844b9c4b249a7cd64d77fad9649b32)

**Comment by moehreag** [comment]
I can't see the impact of this anywhere, it is after all only a warning. Also, you might want to try to further track down which mod (combination) causes this message to appear, I have a feeling it's caused by BetterBiomeBlend instead of this mod.

**Comment by LambdAurora** [comment]
I don't believe this mod causes such thing as such file is not on the classpath of this mod.
