### ISSUE TITLE
1.19.3 support

### ISSUE THREAD

**Issue by RoonMoonlight** [LambdAurora/LambdaBetterGrass#70]
See title

**Comment by LambdAurora** [comment]
It is not compatible, this mod needs a port.

So much as changed for resource packs that I will switch to [Quilt](https://quiltmc.org) for this release as it will make it much easier to port and lower highly the maintenance cost of the mod.
If you were using Fabric, it should be a flawless transition *except if a mod is incompatible but those are a minority*.

At last, while lowering the maintenance cost of the mod, it also means that it will be much more resilient to Minecraft updates, hopefully requiring less needs for ports in the future.

**Comment by RoonMoonlight** [comment]
So no more Fabric release? I'm afraid if Quilt mods are compatible with Fabric...

**Comment by jonask028** [comment]
Almost all fabric mods are compatible with quilt. I have yet to find one that isn't

**Comment by MIPOHBOPOHIH** [comment]
> Almost all fabric mods are compatible with quilt. I have yet to find one that isn't

https://forum.quiltmc.org/t/mod-incompatibility-megathread/261

**Comment by giorov** [comment]
Same, thanks

**Comment by DeltaV-1** [comment]
Is there a possible range of release dates for 1.19.3 support? Like, possibly in the next month or something? I have Sodium but I still like better grass and this is the closest thing I could find to OptiFine's better grass, so I'm just eager for a 1.19.3 compatibility update

**Comment by LambdAurora** [comment]
Given that Mojang decided that 1.19 did not have enough releases, I'm not sure you should get your hopes very high.

Y'all please consider 1.19.2 Long Term Support and anything after until 1.20 is "maybe if I feel like it".  
Quilt will also drop 1.19.3 support once 1.19.4 is out.

**Comment by GitsurferQwerty** [comment]
Well then I guess I'm going to other mods for Better Grass

**Comment by LambdAurora** [comment]
A first step in porting the mod to 1.19.3 has been done: I have ported the existing working version of the mod for 1.19.2 to Quilt, which will simplify porting to 1.19.3.

That was the *easy* part. Maybe 1.19.3 will be easier than anticipated but I can't be sure yet.

**Comment by LambdAurora** [comment]
![image](https://user-images.githubusercontent.com/12587332/214589022-4c108efa-c0c3-4b0d-a9a6-6e3fc8754168.png)

Significant progress has been made, Quilt made this easier indeed.

**Comment by LambdAurora** [comment]
The release is out!

Go download on your favorite platform :3

[Modrinth](https://modrinth.com/mod/lambdabettergrass/version/1.4.0+1.19.3) [CurseForge](https://www.curseforge.com/minecraft/mc-mods/lambdabettergrass/files/4392167) [GitHub](https://github.com/LambdAurora/LambdaBetterGrass/releases/tag/v1.4.0%2B1.19.3)

**Comment by intergrav** [comment]
thank you so much! can't wait to use it again haha
