### ISSUE TITLE
Bug in 1.19.3

### ISSUE THREAD

**Issue by HhiPyrene** [LambdAurora/LambdaBetterGrass#72]
It seems the color of glasses can't be chosen correctly, with LambdaBetterGrass 1.4.0 dev.
[latest.log](https://github.com/LambdAurora/LambdaBetterGrass/files/10518097/latest.log)
![huge_2023-01-27_18 49 58](https://user-images.githubusercontent.com/111572269/215069574-7bc8d6d6-ea4f-448a-90c3-74106bc2f273.png)

**Comment by LambdAurora** [comment]
I'm not sure how this is related to this mod since it doesn't even remotely touch beacons or glass.

I'm also not sure what the bug is about, are the glass textures wrong or just beacon behavior being broken? If the former then I'll investigate further, but the latter is entirely unrelated to the mod.

**Comment by YukiAyase** [comment]
> I'm not sure how this is related to this mod since it doesn't even remotely touch beacons or glass.
> 
> I'm also not sure what the bug is about, are the glass textures wrong or just beacon behavior being broken? If the former then I'll investigate further, but the latter is entirely unrelated to the mod.

The colors of the stained glass seems to be mismatched with the beacon beam color
I've tested it on my own with a build of dev/1.19 LambdaBetterGrass and this bug is definitely not related to this mod

**Comment by HhiPyrene** [comment]
> I'm not sure how this is related to this mod since it doesn't even remotely touch beacons or glass.
> 
> I'm also not sure what the bug is about, are the glass textures wrong or just beacon behavior being broken? If the former then I'll investigate further, but the latter is entirely unrelated to the mod.

The former.
Well, I tested the game and found that the bug produce when use this mod and Dashloader at a same time. Idk wtf Dashloader did, but it's the fact. 
![huge_2023-01-27_19 35 34](https://user-images.githubusercontent.com/111572269/215080518-78103872-3e27-41c2-91cb-13eb85f38ac9.png)

**Comment by HhiPyrene** [comment]
Idk why I can't reproduce. I think close this issue is better.
