### ISSUE TITLE
[Crash/Bug] Crash with EssentialGui

### ISSUE THREAD

**Issue by DanMeadWasTaken** [LambdAurora/LambdaBetterGrass#74]
minecraft 1.19.2/quilt 0.17.11
[LambdaBetterGrass 1.3.0](https://modrinth.com/mod/lambdabettergrass/version/1.3.0%2B1.19)
[EssentialGui 1.8.2](https://www.curseforge.com/minecraft/mc-mods/essentialgui)

look at a grass block and boom crash.
[latest.log](https://mclo.gs/dyNNkBM) 
[crash log](https://mclo.gs/6yxGb6G)

**Comment by LambdAurora** [comment]
The crash report mention that

```
java.lang.IllegalStateException: Cannot get config value before config is loaded
at com.google.common.base.Preconditions.checkState(Preconditions.java:502)
at com.illusivesoulworks.spectrelib.config.SpectreConfigSpec$ConfigValue.get(SpectreConfigSpec.java:1187)
at com.illusivesoulworks.elytrautilities.client.ClientFlightController.isFlightDisabled(ClientFlightController.java:30)
 at net.minecraft.class_746.localvar$daa000$elytrautilities$aiStep(class_746.java:1422)
```

This crash seems to be caused by some mod named ElytraUtilities which fails to get something from its configuration.

This is not related to this mod.

**Comment by DanMeadWasTaken** [comment]
Funny thing about that, elytra utilities is not even in the pack? it had been in the pack, but was causing a crash and so was removed

**Comment by DanMeadWasTaken** [comment]
The crash specifically happens when i look at a block- and as this mentions

![Screenshot_2023-02-09_11-09-28](https://user-images.githubusercontent.com/75497984/217887366-dcb5a9b5-b8a8-4fff-b508-bf90c50f9883.png)


the crash is because lambda grass is trying to show up as an item entity in essential GUI

**Comment by DanMeadWasTaken** [comment]
So, I don't mean to be rude- but please look at a log completely before making an assumption. If you had, you'd have seen that elytra utilities is not in the active mod list, and at the point where the crash happened- the bottom, it points towards a conflict between lambda better grass and essential GUI

**Comment by LambdAurora** [comment]
Don't link an unrelated crash report then.
That log file is filled with so much junk I jumped straight to the crash report instead, since it was unreadable, especially on a mobile phone.

**Comment by LambdAurora** [comment]
Also tell EssentialGUI to not try to render block models as item models and get their actual item models instead or render the block model as a block model.

**Comment by DanMeadWasTaken** [comment]
> Don't link an unrelated crash report then. That log file is filled with so much junk I jumped straight to the crash report instead, since it was unreadable, especially on a mobile phone.

Ah- see, that's on me, prism's layout of logs can be confusing/unreliable. 



> Also tell EssentialGUI to not try to render block models as item models and get their actual item models instead or render the block model as a block model.

I have already made an issue on their curseforge page with the same logs i sent you- granted after realizing the messup, it'd seem i need to go back to that and fix the log link.

~~If you'd like i can pass on your message while I am at it?~~ nvm, would seem curseforge is being a bugger and keeps sending me to their beta version which won't lemme access the built in issues page.

**Comment by DanMeadWasTaken** [comment]
Alright, so i left a note to them as well as the fixed log links. 
![Screenshot_2023-02-09_12-01-52](https://user-images.githubusercontent.com/75497984/217899318-6e491ee9-c0be-4c8a-852b-7f83f671226f.png)
If there is nothing you can do on your end to fix things, then feel free to close this. Sorry for the mistake- and my own attitude before realizing my mistake. I really do like using your mods, It's just sometimes mod developers can be a bit dismissive without looking at issues fully at times, and it can be frustrating. especially when I run into so many bugs/crashes and make more of these reports than I'd like to, and some of them still haven't gotten back to me- granted, i don't blame them, most of the ones who haven't gotten back are a one man/woman team working on a passion project all by themselves. Anyway, sorry for the ramble, i mostly just wanted to apologize.

**Comment by LambdAurora** [comment]
I have to admit I'm not particularly interested in updating for 1.19.2, but I'll remove the exception throwing in future releases even if I think rendering a block model as an item is not good practice. Especially considering that those renders don't have the same contexts which could lead to incorrect renders. (For example, if you take Aurora's Decorations blackboards, rendering its blackboard block model as an item instead of using the item renderer will lead to an inaccurate render since both models have different implementations that cannot be switched.)

**Comment by DanMeadWasTaken** [comment]
I'll go ahead an close this- as it'd seem it had already been fixed on their end- turns out the issue was I apparently had to delete the config file after updating to fix the issue.
