### ISSUE TITLE
LambdaBetterGrass not working

### ISSUE THREAD

**Issue by ghost** [LambdAurora/LambdaBetterGrass#8]
Better grass not working as intended.
![2020-10-02_20 30 43](https://user-images.githubusercontent.com/64201549/94962505-79f8ad00-04ee-11eb-97a3-2ee7ea556e9a.png)
![2020-10-02_20 30 51](https://user-images.githubusercontent.com/64201549/94962516-7e24ca80-04ee-11eb-8a85-d700f217bd5e.png)
![2020-10-02_20 32 20](https://user-images.githubusercontent.com/64201549/94962520-7ebd6100-04ee-11eb-93d4-e268b6e4ebb3.png)

**Comment by ghost** [comment]
Ok, just checked, it's not compatible with Sodium, MB.

**Comment by Rajbir98** [comment]
So its not compatible with sodium

**Comment by Rajbir98** [comment]
And what is MB

**Comment by LambdAurora** [comment]
There's Indium to make it compatible.
