### ISSUE TITLE
Update to 1.19.4

### ISSUE THREAD

**Issue by DeltaV-1** [LambdAurora/LambdaBetterGrass#80]
I know this was probably pretty obvious that you should update to 1.19.4, but this is more a question of how long it will take. Last time you said you needed to port this mod to Quilt to update it to 1.19.3, but now that update 1.19.4 is out will it be a shorter update time?

**Comment by LambdAurora** [comment]
I'll try to make it a shorter update. But I can't guarantee anything since university loves being an absolute nightmare for students.

**Comment by LambdAurora** [comment]
Most of the update is done, just need to check everything again to make sure I haven't missed anything, then I'll release. With some luck might happen tomorrow.

This update adds cherry wood stuff which required some texture work for the built-in resource pack too.

**Comment by DeltaV-1** [comment]
Alrighty. Thank you! 😀

**Comment by LambdAurora** [comment]
I lied, I took more days, was really tired the previous evenings.

But hey, it's out now!

**Comment by Cobyt3** [comment]
Will there be a Fabric Version as well? Currently, only Quilt is updated to 1.19.4

**Comment by LambdAurora** [comment]
No Fabric version as it has significantly more maintenance burden.

[Most Fabric mods work on Quilt though.](https://quiltmc.org/en/about/newcomer-guide/)
