### ISSUE TITLE
Incompatible with EnhancedBlockEntities 1.19.3

### ISSUE THREAD

**Issue by YukiAyase** [LambdAurora/LambdaBetterGrass#83]
After the recent QSL update (QSL 4.0.0-beta.13), EBE issue https://github.com/FoundationGames/EnhancedBlockEntities/issues/136 has been fixed
However, it has shown incompatibility with EBE when having both EBE and LBG installed, the above issue mentioned happens when you have both mods installed

With LBG
![2023-04-05_15 10 53](https://user-images.githubusercontent.com/64414315/230007281-b4240510-0a36-4fb0-8c6e-0ca6e0181c2e.png)

Without LBG
![2023-04-05_15 09 41](https://user-images.githubusercontent.com/64414315/230007315-801655f5-4903-40c5-8988-d7bfa439fd7e.png)

Latest log file with EBE, LBG and QFAPI 5.0.0-beta.9 and QSL 4.0.0-beta.13
https://mclo.gs/EXBvdAq

_Note: I have already reported this to EBE's Discord_

**Comment by LambdAurora** [comment]
As I mentioned in the PR, EBE also has faulty code which needs fixing. The injection uses `INVOKE_ASSIGN` which only modifies one part, while it needs to use `INVOKE`.
