### ISSUE TITLE
[Suggestion] Make "Better Snow Sides" a separate option from Better Snow

### ISSUE THREAD

**Issue by Reyks21** [LambdAurora/LambdaBetterGrass#84]
Currently the Better Snow option applies the snow layer effect under fences and vegetation, however the snow side textures are also tied to this setting. So if I wanted only the nice connecting side textures on the snowy grass blocks I am forced to use the snow layers as well, wich looks really bad when using shaders, especially with waving plants.

My suggestion would be to make a third "Better Snow Sides" option, OR, tie it to the Better Grass setting since it is a snowy GRASS block after all.

**Comment by LambdAurora** [comment]
It's already tied to the better grass option?

**Comment by Reyks21** [comment]
Maybe it was at some point but right now it only works with Better Snow turned on:

**Better Snow = On**
![2023-04-26_11 54 19](https://user-images.githubusercontent.com/10340735/234616045-115c7814-e3b6-4137-a578-1caafda010ed.png)

**Better Snow = Off**
![2023-04-26_11 54 38](https://user-images.githubusercontent.com/10340735/234616389-4fd80b0b-abd8-4b65-bf0e-2a9421173a88.png)

This is without any resource pack btw, only the one that comes with the mod.

**Comment by LambdAurora** [comment]
This is weird, the blocks with  snow on top of them should be snowy?

But normal grass not connecting to snowy grass is intentional so far, might look into an option to make it connect if I can make it easily. I just thought it was silly to have an entire green face connected to snow.

**Comment by Reyks21** [comment]
Well yeah I dont think it should connect to regular grass, but maybe only connect to other snowy grass blocks with better grass=on? If thats even possible.

And no idea why some grass blocks with snow on top arent snowy lol, could be a Terralith worldgen error.

**Comment by LambdAurora** [comment]
That's not worldgen error. I think here there's a massive bug happening.

Now I understand and it's really a bug. I have no idea why some of those are not snowy nor why they don't connect properly.
If you could do a minimum example and send the log file that would be nice.

**Comment by Reyks21** [comment]
Well its happening even with the mod completely disabled in Prism Launcher, so I'm not sure what this is.

Mod on
![2023-04-27_14 53 30](https://user-images.githubusercontent.com/10340735/234951488-c2bfb3fb-2c73-48b8-865c-f736e573b939.png)

Mod off
![2023-04-27_14 54 46](https://user-images.githubusercontent.com/10340735/234951525-a3443894-5506-4792-8860-31e7872ef237.png)

Anyway here's a log: https://mclo.gs/8qus1FI

**Comment by Reyks21** [comment]
Hey just wanted to update you, I removed terralith and the snow bug is gone, so it was probably a worldgen issue with that mod.
