### ISSUE TITLE
Add 1.20.1 Fabric support

### ISSUE THREAD

**Issue by SorkoPiko** [LambdAurora/LambdaBetterGrass#87]
If you could add 1.20.1 support for Fabric, that would be great. Thanks!

**Comment by LambdAurora** [comment]
Install [Quilt](https://quiltmc.org).

**Comment by jessestricker** [comment]
Quilt is still in beta, please consider supporting Fabric until Quilt is declared stable.

**Comment by Fnige** [comment]
> Quilt is still in beta, please consider supporting Fabric until Quilt is declared stable.

It considered and the conclusion was no (◡‿◡✿)
